# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  push:
    tags:
      - "*.*.*.*" # First star is the package name, then the version number.

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Extract package name and version number from tag
        id: extract_info
        run: |
          TAG=${{ github.ref_name }}
          # Extract the package name (everything before the first dot)
          PACKAGE=$(echo "${TAG}" | cut -d'.' -f1)
          # Extract the version number (everything after the first dot)
          VERSION=$(echo "${TAG}" | cut -d'.' -f2-)
          
          echo "Package name extracted: ${PACKAGE}"
          echo "Version number extracted: ${VERSION}"
          
          # Make the PACKAGE and VERSION variables available to other steps
          echo "PACKAGE_NAME=${PACKAGE}" >> $GITHUB_ENV
          echo "VERSION_NUMBER=${VERSION}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: cd ./GP.$PACKAGE_NAME && dotnet build --configuration Release

      - name: Package
        working-directory: ./GP.$PACKAGE_NAME
        run: dotnet pack --no-restore --no-build --configuration Release -p:PackageVersion=$VERSION_NUMBER --output .

      - name: Publish
        working-directory: ./GP.$PACKAGE_NAME
        run: >
          dotnet nuget push GorboPackages.${{ github.ref_name }}.nupkg
          -s https://nuget.pkg.github.com/PI-Gorbo/index.json
          -k ${{ secrets.NUGET_REPO_AUTH }}
